
const aktuColleges = [
    // Top Government Colleges
    "IET Lucknow",
    "KNIT Sultanpur",
    "BIET Jhansi",
    "HBTU Kanpur",
    "MMMUT Gorakhpur",

    // Ghaziabad Region
    "AKGEC Ghaziabad",
    "KIET Ghaziabad",
    "ABES Engineering College Ghaziabad",
    "Krishna Engineering College Ghaziabad",
    "RKGIT Ghaziabad",
    "IMS Engineering College Ghaziabad",
    "RD Engineering College Ghaziabad",
    "IPEC Ghaziabad",
    "ABESIT Ghaziabad",
    "Sharda University Greater Noida",

    // Greater Noida/Noida Region
    "Galgotias College Greater Noida",
    "Galgotias University Greater Noida",
    "GL Bajaj Greater Noida",
    "GNIOT Greater Noida",
    "NIET Greater Noida",
    "Shiv Nadar University Greater Noida",
    "JSS Noida",
    "BVCOE Greater Noida",
    "Accurate Institute Greater Noida",
    "IMS Engineering College Greater Noida",

    // Lucknow Region
    "SRMCEM Lucknow",
    "BBD University Lucknow",
    "Babu Banarasi Das Engineering College Lucknow",
    "IET Lucknow",
    "Amity University Lucknow",
    "Integral University Lucknow",
    "MPEC Kanpur",
    "HBTI Kanpur",

    // Meerut Region
    "ITS Engineering College Meerut",
    "MIET Meerut",
    "Subharti University Meerut",
    "RKGITW Ghaziabad",
    "Accurate Group Meerut",
    "COER Roorkee",

    // Moradabad Region
    "IET Bareilly",
    "BTKIT Dwarahat",
    "Invertis University Bareilly",
    "GCET Greater Noida",

    // Agra Region
    "RBS Engineering College Agra",
    "BIET Jhansi",
    "SIET Allahabad",

    // Other Major Colleges
    "Buddha Institute Gorakhpur",
    "Pranveer Singh Institute Kanpur",
    "PSIT Kanpur",
    "KCC Institute Greater Noida",
    "Lloyd Institute Greater Noida",
    "Mangalmay Institute Greater Noida",
    "KIET Group Muradnagar",
    "IIMT Engineering College Meerut",
    "AITH Kanpur",
    "GCET Greater Noida",
    "United College Allahabad",
    "IEC Greater Noida",
    "Shri Ram Group Muzaffarnagar",
    "NIET Pharmacy Greater Noida",
    "IIMT Greater Noida",
    "JSS Academy Noida",
    "Dronacharya Group Greater Noida",
    "IILM Greater Noida",
    "Azad Institute Lucknow",
    "SRMS CET Bareilly",
    "BBDNITM Lucknow",
    "KNIT Sultanpur",
    "GCET Greater Noida",
    "Hindustan College Mathura",
    "REC Kanpur",
    "NIET Greater Noida",
    "BBDEC Lucknow",
    "SHIATS Allahabad",
    "Dr. MCET Moradabad",
    "MPGI Kanpur",
    "SIET Allahabad",
    "BCET Lucknow",
    "IERT Allahabad",
    "NIET Greater Noida",
    "FET Agra",
    "BBDGEI Lucknow",
    "SHIATS Allahabad",
    "IIT BHU Varanasi",
    "Faculty of Engineering Dayalbagh Agra",
    "KNIT Sultanpur",
    "Ajay Kumar Garg Engineering College Ghaziabad",
    "MLN College Allahabad",
    "RGPV Bhopal",
    "Kamla Nehru Institute Sultanpur",
    "MPEC Kanpur",
    "BBDNITM Lucknow",
    "PSIT Kanpur",
    "BBD Government Engineering College Lucknow",
    "HBTI Kanpur",
    "SRMGPC Lucknow",
    "Krishna Institute Ghaziabad",
    "IMS Ghaziabad",
    "NIET Greater Noida",
    "Moradabad Institute Moradabad"
];

export default aktuColleges;
